# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "apply_key_mapping",
]

def apply_key_mapping(data: typing.Any, mapping: dict) -> typing.Any: ...

