# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

def apply_key_mapping(
    data: dict, mapping: typing.Mapping[builtins.str, builtins.str]
) -> typing.Any: ...
